### ISSUE TITLE
Demo page cannot import 'imageToBlob'

### ISSUE THREAD

**Issue by shisama** [GoogleChromeLabs/browser-nativefs#17]
Hi, I read [this article](https://web.dev/browser-nativefs/). Thank you for writing an interesting article and your contributions to the new Native File System API. However, I couldn't try [demo page](https://courageous-cooing-astronaut.glitch.me/) on Chrome (86.0.4220.0（Official Build）canary （x86_64）).
Console shows me the below error message.

```
Uncaught SyntaxError: The requested module 'https://unpkg.com/browser-nativefs' does not provide an export named 'imageToBlob'
```

I guess that `imageToBlob` cannot be used due to [this change](https://github.com/GoogleChromeLabs/browser-nativefs/pull/16/files#diff-1fdf421c05c1140f6d71444ea2b27638L24) (#16).

If the demo page was broken unintentionally, please fix the demo page or export `imageToBlob`.

**Comment by tomayac** [comment]
Thanks for the report! I have fixed the [demo](https://browser-nativefs.glitch.me/). I indeed forgot to fix the `import` after the commit you mentioned.
