### ISSUE TITLE
Possible to use in Chrome extension?

### ISSUE THREAD

**Issue by GreenFootballs** [GoogleChromeLabs/browser-nativefs#19]
Hi, this is a great little library, but since it uses import to do its thing, it's difficult if not impossible to use in a Chrome extension (which I'm currently developing), because there's no way to set the file type to 'module' in the extension manifest. This needs to run in the content script, and injecting a script tag into the DOM has some big limitations.

Is there any way to use the current code in an extension, or could parts of it be extracted to work as simple functions in a standard JS file?

**Comment by tomayac** [comment]
It should be possible to use modules in extensions. This [article](https://medium.com/front-end-weekly/es6-modules-in-chrome-extensions-an-introduction-313b3fce955b) outlines the general steps for all components. Note the update that references this [post](https://stackoverflow.com/questions/48104433/how-to-import-es6-modules-in-content-script-for-chrome-extension/48121629#48121629) for content scripts. I'm closing this issue for now, but feel free to comment further and I am happy to provide help if need be.

**Comment by tomayac** [comment]
Oh, and at the risk of pointing out the obvious: you can of course just use a bundler like [rollup.js](https://rollupjs.org/guide/en/#quick-start:~:text=For%20browsers%3A).

**Comment by GreenFootballs** [comment]
Thanks, I got it to work! I was having lots of trouble trying to use dynamic import with the code as is, but rollup.js was the magic I needed. This is the command line I used to generate the file:

rollup ./src/index.js --file ./bundle/nativefs.js --inlineDynamicImports

**Comment by tomayac** [comment]
Thanks for reporting back on your success! Happy you got this working for you!
