### ISSUE TITLE
fileSave doesn't write correct mimeType for custom extensions

### ISSUE THREAD

**Issue by dwelle** [GoogleChromeLabs/browser-nativefs#24]
I'm not sure if this is a problem with Native FS API or something else, but if you save a blob with a given mimeType, but a custom extension, the file will end up with an empty/missing mimeType (when later opened, for example).

This should be reported upstream/crbug — just wanted to make sure I'm not missing something, first.

```js
fileSave(new Blob([], { type: "application/json" }), {
    fileName: "test",
    extensions: [".excalidraw"]
})

const blob = await fileOpen({
    // if you comment this it won't even show the file
    // in file picker because of missing mimeType
    extensions: [".excalidraw"],
    mimeTypes: ["application/json"]
});
setType(blob.type); // ""
```

Repro: https://0cglk.csb.app/
Source: https://codesandbox.io/s/sharp-bartik-0cglk?file=/src/App.js (due to security, use the link above to test)

**Comment by tomayac** [comment]
Under the hood, this is the code browser-nativefs creates for this:

```js
const handle =    
    (await window.showSaveFilePicker({
      types: [
        {          
          accept: {
            ['application/json']: ['.excalidraw'],
          },
        },
      ],
    }));
const writable = await handle.createWritable();
await writable.write(new Blob(["{a:0}"], {type: 'application/json'}));
await writable.close();
```

The way operating systems like macOS handle this is to give preference to the extension. See how macOS behaves if I change `.png` to `.custompng`. The MIME type macOS displays downgrades from "PNG image" (`image/png`) to "Document", which is its way of saying `🤷‍♀️/🤷‍♂️`:

<img width="454" alt="Screen Shot 2020-10-19 at 10 26 11" src="https://user-images.githubusercontent.com/145676/96420308-a2262280-11f5-11eb-8933-37b9aed32f9a.png">
<img width="435" alt="Screen Shot 2020-10-19 at 10 26 37" src="https://user-images.githubusercontent.com/145676/96420313-a3574f80-11f5-11eb-9790-5543e5841906.png">

**Comment by dwelle** [comment]
I see. I thought it might be the OS messing it up, but I thought browser or whatever API does the actual writing does have a say and can override the MIME type if it chooses to do so :(.

**Comment by tomayac** [comment]
MIME type are considered a serious thing that not everyone can freely mess around with, but that need to follow strict [processes](https://www.iana.org/assignments/media-types/media-types.xhtml#:~:text=Procedures%20for%20registering%20Media%20Types%20can,and%20%5BRFC6657%5D.) for registering. Each MIME type has a set of registered extensions ([example for `application/json`](https://www.iana.org/assignments/media-types/application/json#:~:text=File%20extension(s)%3A%20.json)). Anything else won't be considered by operating systems.

**Comment by dwelle** [comment]
I kinda knew about not being able to create your own MIME types on the fly, but naively (my turn) thought that matching file extensions aren't required to reuse an existing MIME type (in our case, `application/json`). Thanks for setting me straight :).
