### ISSUE TITLE
options.fileName not used in file save 

### ISSUE THREAD

**Issue by arpu** [GoogleChromeLabs/browser-nativefs#27]
Hey,

how can i use the options.fileName on the 
window.showSaveFilePicker
https://github.com/GoogleChromeLabs/browser-nativefs/blob/master/src/nativefs/file-save.mjs#L23

**Comment by tomayac** [comment]
This will work once the underlying [issue](https://github.com/WICG/file-system-access/issues/80) in the File System Access API gets resolved. Please subscribe to that issue to be updated of changes.

**Comment by arpu** [comment]
thx for the hint!

is there a way i can create the file on a directory handler with the filename?

**Comment by tomayac** [comment]
This should be [possible](https://web.dev/file-system-access/#creating-or-accessing-files-and-folders-in-a-directory), yes. Just note that this obviously only works on browsers that support the File System Access API, whereas `browser-nativefs` (the library in this repo) tries to have a reasonable fallback behavior for people on browsers that don't support the API.

**Comment by arpu** [comment]
perfect! will try this with latest chrome
